### PR TITLE
Release 0.1.14

### PR DESCRIPTION
**Pull request by casey**
- Bump version: 0.1.13 → 0.1.14
- Update changelog
- Update changelog contributor credits

### CODE REVIEW

**Comment by quietvoid** [comment]
FYI all the links in the changelog and release are in the `filepack` repo, not here.

**Comment by casey** [comment]
T_T

**Comment by casey** [comment]
Thanks for reporting, I'll fix that.

**Comment by casey** [comment]
Fixed in #544!

**Pull request merged**
