### PR TITLE
Add Void Linux package to README

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**
I'll undraft this once https://github.com/void-linux/void-packages/pull/24520 is merged.

### CODE REVIEW

**Comment by casey** [comment]
Awesome. Thank you so much for packaging Intermodal for Void!

**Comment by casey** [comment]
It looks like the package was added in this commit:

https://github.com/void-linux/void-packages/commit/f93f68b79d26ae7555723013391a51a8f59bf417

Is that correct?

**Comment by ThatNerdyPikachu** [comment]
Correct.

**Comment by casey** [comment]
Merged! Thank you very much!

**Pull request merged**
